/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated with
    libedssharp Object Dictionary Editor v0.8-125-g85dfd8e

    https://github.com/CANopenNode/CANopenNode
    https://github.com/robincornelius/libedssharp

    DON'T EDIT THIS FILE MANUALLY, UNLESS YOU KNOW WHAT YOU ARE DOING !!!!
*******************************************************************************/

#define OD_DEFINITION
// #include "301/CO_ODinterface.h"

#include "OD.hpp"
#include <stddef.h>

/*******************************************************************************
    OD data initialization of all groups
*******************************************************************************/
OD_PERSIST_COMM_t OD_PERSIST_COMM = {
    .x1000_deviceType                      = 0x00000192,
    .x1005_COB_ID_SYNCMessage              = 0x00000080,
    .x1006_communicationCyclePeriod        = 0x00000000,
    .x1007_synchronousWindowLength         = 0x00000000,
    .x1008_manufacturerDeviceName          = {'M', 'D', '8', '0', 0},
    .x1009_manufacturerHardwareVersion     = {'0', 0},
    .x1012_COB_IDTimeStampObject           = 0x00000100,
    .x1014_COB_ID_EMCY                     = 0x00000080,
    .x1015_inhibitTimeEMCY                 = 0x0000,
    .x1016_consumerHeartbeatTime_sub0      = 0x08,
    .x1016_consumerHeartbeatTime           = {0x00000000,
                                              0x00000000,
                                              0x00000000,
                                              0x00000000,
                                              0x00000000,
                                              0x00000000,
                                              0x00000000,
                                              0x00000000},
    .x1017_producerHeartbeatTime           = 0x03E8,
    .x1018_identity                        = {.highestSub_indexSupported = 0x04,
                                              .vendor_ID                 = 0x00000000,
                                              .productCode               = 0x00000000,
                                              .revisionNumber            = 0x00000000,
                                              .serialNumber              = 0x00000000},
    .x1019_synchronousCounterOverflowValue = 0x00,
    .x1280_SDOClientParameter              = {.highestSub_indexSupported = 0x03,
                                              .COB_IDClientToServerTx    = 0x80000000,
                                              .COB_IDServerToClientRx    = 0x80000000,
                                              .node_IDOfTheSDOServer     = 0x01},
    .x1400_RPDOCommunicationParameter      = {.maxSub_index     = 0x06,
                                              .COB_IDUsedByRPDO = 0x00000200,
                                              .transmissionType = 0xFE},
    .x1401_RPDOCommunicationParameter      = {.maxSub_index     = 0x06,
                                              .COB_IDUsedByRPDO = 0x00000300,
                                              .transmissionType = 0xFE},
    .x1402_RPDOCommunicationParameter      = {.maxSub_index     = 0x06,
                                              .COB_IDUsedByRPDO = 0x00000400,
                                              .transmissionType = 0xFE},
    .x1403_RPDOCommunicationParameter      = {.maxSub_index     = 0x06,
                                              .COB_IDUsedByRPDO = 0x00000500,
                                              .transmissionType = 0xFE},
    .x1600_RPDOMappingParameter            = {.numberOfMappedObjects = 0x01,
                                              .mappedObject_1        = 0x60FF0020,
                                              .mappedObject_2        = 0x00000000,
                                              .mappedObject_3        = 0x00000000,
                                              .mappedObject_4        = 0x00000000,
                                              .mappedObject_5        = 0x00000000,
                                              .mappedObject_6        = 0x00000000,
                                              .mappedObject_7        = 0x00000000,
                                              .mappedObject_8        = 0x00000000},
    .x1601_RPDOMappingParameter            = {.numberOfMappedObjects = 0x02,
                                              .mappedObject_1        = 0x60400010,
                                              .mappedObject_2        = 0x60600008,
                                              .mappedObject_3        = 0x00000000,
                                              .mappedObject_4        = 0x00000000,
                                              .mappedObject_5        = 0x00000000,
                                              .mappedObject_6        = 0x00000000,
                                              .mappedObject_7        = 0x00000000,
                                              .mappedObject_8        = 0x00000000},
    .x1602_RPDOMappingParameter            = {.numberOfMappedObjects = 0x02,
                                              .mappedObject_1        = 0x60400010,
                                              .mappedObject_2        = 0x607A0020,
                                              .mappedObject_3        = 0x00000000,
                                              .mappedObject_4        = 0x00000000,
                                              .mappedObject_5        = 0x00000000,
                                              .mappedObject_6        = 0x00000000,
                                              .mappedObject_7        = 0x00000000,
                                              .mappedObject_8        = 0x00000000},
    .x1603_RPDOMappingParameter            = {.numberOfMappedObjects = 0x02,
                                              .mappedObject_1        = 0x60400010,
                                              .mappedObject_2        = 0x60FF0020,
                                              .mappedObject_3        = 0x00000000,
                                              .mappedObject_4        = 0x00000000,
                                              .mappedObject_5        = 0x00000000,
                                              .mappedObject_6        = 0x00000000,
                                              .mappedObject_7        = 0x00000000,
                                              .mappedObject_8        = 0x00000000},
    .x1800_TPDOCommunicationParameter      = {.maxSub_index       = 0x06,
                                              .COB_IDUsedByTPDO   = 0x00000180,
                                              .transmissionType   = 0xFE,
                                              .inhibitTime        = 0x0000,
                                              .compatibilityEntry = 0x00,
                                              .eventTimer         = 0x0000,
                                              .SYNCStartValue     = 0x00},
    .x1801_TPDOCommunicationParameter      = {.maxSub_index       = 0x06,
                                              .COB_IDUsedByTPDO   = 0x00000280,
                                              .transmissionType   = 0xFE,
                                              .inhibitTime        = 0x0000,
                                              .compatibilityEntry = 0x00,
                                              .eventTimer         = 0x0000,
                                              .SYNCStartValue     = 0x00},
    .x1802_TPDOCommunicationParameter      = {.maxSub_index       = 0x06,
                                              .COB_IDUsedByTPDO   = 0x00000380,
                                              .transmissionType   = 0xFE,
                                              .inhibitTime        = 0x0000,
                                              .compatibilityEntry = 0x00,
                                              .eventTimer         = 0x0000,
                                              .SYNCStartValue     = 0x00},
    .x1803_TPDOCommunicationParameter      = {.maxSub_index       = 0x06,
                                              .COB_IDUsedByTPDO   = 0x00000480,
                                              .transmissionType   = 0xFE,
                                              .inhibitTime        = 0x0000,
                                              .compatibilityEntry = 0x00,
                                              .eventTimer         = 0x0000,
                                              .SYNCStartValue     = 0x00},
    .x1A00_TPDOMappingParameter            = {.numberOfMappedObjects = 0x01,
                                              .mappedObject_1        = 0x60410010,
                                              .mappedObject_2        = 0x00000000},
    .x1A01_TPDOMappingParameter            = {.numberOfMappedObjects = 0x02,
                                              .mappedObject_1        = 0x60410010,
                                              .mappedObject_2        = 0x60640020},
    .x1A02_TPDOMappingParameter            = {.numberOfMappedObjects = 0x02,
                                              .mappedObject_1        = 0x60410010,
                                              .mappedObject_2        = 0x606C0020},
    .x1A03_TPDOMappingParameter            = {
                   .numberOfMappedObjects = 0x02, .mappedObject_1 = 0x60410010, .mappedObject_2 = 0x60770010}};

OD_RAM_t OD_RAM = {
    .x1001_errorRegister                 = 0x00,
    .x1010_storeParameters_sub0          = 0x04,
    .x1010_storeParameters               = {0x00000001, 0x00000001, 0x00000001, 0x00000001},
    .x1011_restoreDefaultParameters_sub0 = 0x04,
    .x1011_restoreDefaultParameters      = {0x00000001, 0x00000001, 0x00000001, 0x00000001},
    .x1200_SDOServerParameter            = {.highestSub_indexSupported = 0x02,
                                            .COB_IDClientToServerRx    = 0x00000600,
                                            .COB_IDServerToClientTx    = 0x00000580},
    .x1201_SDOServerParameter            = {.highestSub_indexSupported = 0x02,
                                            .COB_IDClientToServerRx    = 0x00000600,
                                            .COB_IDServerToClientTx    = 0x00000580},
    .x2000_motorSettings                 = {.highestSub_indexSupported = 0x0D,
                                            .polePairs                 = 0x00000000,
                                            .torqueConstant            = 0,
                                            .phaseInductance           = 0,
                                            .phaseResistance           = 0,
                                            .torqueBandwidth           = 0x0000,
                                            .motorName                 = {'M', 'D', '8', '0', 0},
                                            .motorShutdownTemperature  = 0x50,
                                            .gearRatio                 = 1,
                                            .calibrationMode           = 0x00,
                                            .canID                     = 0x00000001,
                                            .canBaudrate               = 0x00000001,
                                            .canWatchdog               = 0x0001,
                                            .reverseDirection          = false},
    .x2001_velocityPID_Controller =
        {.highestSub_indexSupported = 0x04, .kp = 0, .ki = 0, .kd = 0, .integralLimit = 0},
    .x2002_positionPID_Controller =
        {.highestSub_indexSupported = 0x04, .kp = 0, .ki = 0, .kd = 0, .integralLimit = 0},
    .x2003_systemCommand           = {.highestSub_indexSupported   = 0x0D,
                                      .blinkLEDs                   = false,
                                      .resetController             = false,
                                      .runCalibration              = false,
                                      .runOutputEncoderCalibration = false,
                                      .setZero                     = false,
                                      .calibrateCurrentPI_Gains    = false,
                                      .testOutputEncoder           = false,
                                      .testMainEncoder             = false,
                                      .saveMemory                  = false,
                                      .revertFactorySettings       = false,
                                      .clearErrors                 = false,
                                      .clearWarnings               = false,
                                      .runCanReinit                = false},
    .x2004_systemStatus            = {.highestSub_indexSupported = 0x08,
                                      .mainEncoderStatus         = 0x00000000,
                                      .outputEncoderStatus       = 0x00000000,
                                      .calibrationStatus         = 0x00000000,
                                      .bridgeStatus              = 0x00000000,
                                      .hardwareStatus            = 0x00000000,
                                      .homingStatus              = 0x00000000,
                                      .motionStatus              = 0x00000000,
                                      .communicationStatus       = 0x00000000},
    .x2005_outputEncoder           = {.highestSub_indexSupported = 0x05,
                                      .type                      = 0x00,
                                      .calibrationMode           = 0x00,
                                      .mode                      = 0x00,
                                      .position                  = 0,
                                      .velocity                  = 0},
    .x2006_temperature             = {.highestSub_indexSupported = 0x02,
                                      .motorTemperature          = 0,
                                      .mosfetTemperature         = 0},
    .x2007_limits                  = {.highestSub_indexSupported = 0x06,
                                      .maxTorque                 = 0,
                                      .maxAcceleration           = 0,
                                      .maxDeceleration           = 0,
                                      .maxVelocity               = 0,
                                      .maxPosition               = 0,
                                      .minPosition               = 0},
    .x2008_motion                  = {.highestSub_indexSupported = 0x0B,
                                      .modeCommand               = 0x00,
                                      .modeStatus                = 0x00,
                                      .profileVelocity           = 0,
                                      .profileAcceleration       = 0,
                                      .profileDeceleration       = 0,
                                      .quickStopDeceleration     = 0,
                                      .positionWindow            = 0,
                                      .velocityWindow            = 0,
                                      .targetPosition            = 0,
                                      .targetVelocity            = 0,
                                      .targetTorque              = 0},
    .x2009_motorMesurements        = {.highestSub_indexSupported = 0x03,
                                      .outputPosition            = 0,
                                      .outputVelocity            = 0,
                                      .outputTorque              = 0},
    .x200A_firmwareInfo            = {.highestSub_indexSupported = 0x03,
                                      .commitHash                = {'0', 0},
                                      .buildDate                 = 0x00000000,
                                      .version                   = 0x00000000},
    .x200B_bootloderInfo           = {.highestSub_indexSupported = 0x04,
                                      .bootloaderFixed           = false,
                                      .commitHash                = {'0', 0},
                                      .buildDate                 = 0x00000000,
                                      .version                   = 0x00000000},
    .x200C_impedancePD_Controller  = {.highestSub_indexSupported = 0x02, .kp = 0, .kd = 0},
    .x200D_userGPIO                = {.highestSub_indexSupported = 0x02,
                                      .userGPIO_Configuration    = 0x00,
                                      .userGPIO_State            = 0x0000},
    .x200E_DCBusVoltage            = 0,
    .x6040_controlword             = 0x0000,
    .x6041_statusword              = 0x0000,
    .x6060_modesOfOperation        = 0,
    .x6061_modesOfOperationDisplay = 0,
    .x6062_positionDemandValue     = 0,
    .x6064_positionValue           = 0,
    .x6067_positionWindow          = 0x00000000,
    .x606B_velocityDemandValue     = 0,
    .x606C_velocityActualValue     = 0,
    .x606D_velocityWindow          = 0x00000000,
    .x6072_maxTorque               = 0x0000,
    .x6073_maxCurrent              = 0x0000,
    .x6074_torqueDemandValue       = 0,
    .x6075_motorRatedCurrent       = 0x00000000,
    .x6076_motorRatedTorque        = 0x00000000,
    .x6077_torqueActualValue       = 0,
    .x6079_DClinkCircuitVoltage    = 0x00000000,
    .x607A_targetPosition          = 0,
    .x607D_softwarePositionLimit   = {.highestSub_indexSupported = 0x02,
                                      .minPositionLimit          = -2147483648,
                                      .maxPositionLimit          = 2147483647},
    .x6080_maxMotorSpeed           = 0x000003E8,
    .x6081_profileVelocity         = 0x00000000,
    .x6083_profileAcceleration     = 0x00000000,
    .x6084_profileDeceleration     = 0x00000000,
    .x6085_quickStopDeceleration   = 0x00002710,
    .x60C5_maxAcceleration         = 0x00000000,
    .x60C6_maxDeceleration         = 0x00000000,
    .x60FF_targetVelocity          = 0,
    .x6502_supportedDriveModes     = 0x00000287};

/*******************************************************************************
    All OD objects (constant definitions)
*******************************************************************************/

#include <stdint.h>  // Pour uint16_t, uint8_t

#ifndef CO_PROGMEM
#if defined(__AVR__)
#define CO_PROGMEM __attribute__((__progmem__))
#else
#define CO_PROGMEM
#endif
#endif

typedef struct
{
    OD_obj_var_t    o_1000_deviceType;
    OD_obj_var_t    o_1001_errorRegister;
    OD_obj_array_t  o_1003_pre_definedErrorField;
    OD_obj_var_t    o_1005_COB_ID_SYNCMessage;
    OD_obj_var_t    o_1006_communicationCyclePeriod;
    OD_obj_var_t    o_1007_synchronousWindowLength;
    OD_obj_var_t    o_1008_manufacturerDeviceName;
    OD_obj_var_t    o_1009_manufacturerHardwareVersion;
    OD_obj_array_t  o_1010_storeParameters;
    OD_obj_array_t  o_1011_restoreDefaultParameters;
    OD_obj_var_t    o_1012_COB_IDTimeStampObject;
    OD_obj_var_t    o_1014_COB_ID_EMCY;
    OD_obj_var_t    o_1015_inhibitTimeEMCY;
    OD_obj_array_t  o_1016_consumerHeartbeatTime;
    OD_obj_var_t    o_1017_producerHeartbeatTime;
    OD_obj_record_t o_1018_identity[5];
    OD_obj_var_t    o_1019_synchronousCounterOverflowValue;
    OD_obj_record_t o_1200_SDOServerParameter[3];
    OD_obj_record_t o_1201_SDOServerParameter[3];
    OD_obj_record_t o_1280_SDOClientParameter[4];
    OD_obj_record_t o_1400_RPDOCommunicationParameter[3];
    OD_obj_record_t o_1401_RPDOCommunicationParameter[3];
    OD_obj_record_t o_1402_RPDOCommunicationParameter[3];
    OD_obj_record_t o_1403_RPDOCommunicationParameter[3];
    OD_obj_record_t o_1600_RPDOMappingParameter[9];
    OD_obj_record_t o_1601_RPDOMappingParameter[9];
    OD_obj_record_t o_1602_RPDOMappingParameter[9];
    OD_obj_record_t o_1603_RPDOMappingParameter[9];
    OD_obj_record_t o_1800_TPDOCommunicationParameter[7];
    OD_obj_record_t o_1801_TPDOCommunicationParameter[7];
    OD_obj_record_t o_1802_TPDOCommunicationParameter[7];
    OD_obj_record_t o_1803_TPDOCommunicationParameter[7];
    OD_obj_record_t o_1A00_TPDOMappingParameter[3];
    OD_obj_record_t o_1A01_TPDOMappingParameter[3];
    OD_obj_record_t o_1A02_TPDOMappingParameter[3];
    OD_obj_record_t o_1A03_TPDOMappingParameter[3];
    OD_obj_record_t o_2000_motorSettings[14];
    OD_obj_record_t o_2001_velocityPID_Controller[5];
    OD_obj_record_t o_2002_positionPID_Controller[5];
    OD_obj_record_t o_2003_systemCommand[14];
    OD_obj_record_t o_2004_systemStatus[9];
    OD_obj_record_t o_2005_outputEncoder[6];
    OD_obj_record_t o_2006_temperature[3];
    OD_obj_record_t o_2007_limits[7];
    OD_obj_record_t o_2008_motion[12];
    OD_obj_record_t o_2009_motorMesurements[4];
    OD_obj_record_t o_200A_firmwareInfo[4];
    OD_obj_record_t o_200B_bootloderInfo[5];
    OD_obj_record_t o_200C_impedancePD_Controller[3];
    OD_obj_record_t o_200D_userGPIO[3];
    OD_obj_var_t    o_200E_DCBusVoltage;
    OD_obj_var_t    o_6040_controlword;
    OD_obj_var_t    o_6041_statusword;
    OD_obj_var_t    o_6060_modesOfOperation;
    OD_obj_var_t    o_6061_modesOfOperationDisplay;
    OD_obj_var_t    o_6062_positionDemandValue;
    OD_obj_var_t    o_6064_positionValue;
    OD_obj_var_t    o_6067_positionWindow;
    OD_obj_var_t    o_606B_velocityDemandValue;
    OD_obj_var_t    o_606C_velocityActualValue;
    OD_obj_var_t    o_606D_velocityWindow;
    OD_obj_var_t    o_6072_maxTorque;
    OD_obj_var_t    o_6073_maxCurrent;
    OD_obj_var_t    o_6074_torqueDemandValue;
    OD_obj_var_t    o_6075_motorRatedCurrent;
    OD_obj_var_t    o_6076_motorRatedTorque;
    OD_obj_var_t    o_6077_torqueActualValue;
    OD_obj_var_t    o_6079_DClinkCircuitVoltage;
    OD_obj_var_t    o_607A_targetPosition;
    OD_obj_record_t o_607D_softwarePositionLimit[3];
    OD_obj_var_t    o_6080_maxMotorSpeed;
    OD_obj_var_t    o_6081_profileVelocity;
    OD_obj_var_t    o_6083_profileAcceleration;
    OD_obj_var_t    o_6084_profileDeceleration;
    OD_obj_var_t    o_6085_quickStopDeceleration;
    OD_obj_var_t    o_60C5_maxAcceleration;
    OD_obj_var_t    o_60C6_maxDeceleration;
    OD_obj_var_t    o_60FF_targetVelocity;
    OD_obj_var_t    o_6502_supportedDriveModes;
} ODObjs_t;

#define ODA_SDO_R  0x01U  /**< SDO server may read from the variable */
#define ODA_SDO_W  0x02U  /**< SDO server may write to the variable */
#define ODA_SDO_RW 0x03U  /**< SDO server may read from or write to the variable */
#define ODA_TPDO   0x04U  /**< Variable is mappable into TPDO (can be read) */
#define ODA_RPDO   0x08U  /**< Variable is mappable into RPDO (can be written) */
#define ODA_TRPDO  0x0CU  /**< Variable is mappable into TPDO or RPDO */
#define ODA_TSRDO  0x10U  /**< Variable is mappable into transmitting SRDO */
#define ODA_RSRDO  0x20U  /**< Variable is mappable into receiving SRDO */
#define ODA_TRSRDO 0x30U  /**< Variable is mappable into tx or rx SRDO */
#define ODA_MB     0x40U  /**< Variable is multi-byte ((u)int16_t to (u)int64_t) */
#define ODA_STR    0x80U  //< Shorter value, than specified variable size, may be written to the

static CO_PROGMEM ODObjs_t ODObjs = {
    .o_1000_deviceType               = {.dataOrig   = &OD_PERSIST_COMM.x1000_deviceType,
                                        .attribute  = ODA_SDO_R | ODA_MB,
                                        .dataLength = 4},
    .o_1001_errorRegister            = {.dataOrig   = &OD_RAM.x1001_errorRegister,
                                        .attribute  = ODA_SDO_R | ODA_TRPDO,
                                        .dataLength = 1},
    .o_1003_pre_definedErrorField    = {.dataOrig0         = NULL,
                                        .dataOrig          = NULL,
                                        .attribute0        = ODA_SDO_RW,
                                        .attribute         = ODA_SDO_R | ODA_MB,
                                        .dataElementLength = 4,
                                        .dataElementSizeof = sizeof(uint32_t)},
    .o_1005_COB_ID_SYNCMessage       = {.dataOrig   = &OD_PERSIST_COMM.x1005_COB_ID_SYNCMessage,
                                        .attribute  = ODA_SDO_RW | ODA_MB,
                                        .dataLength = 4},
    .o_1006_communicationCyclePeriod = {.dataOrig = &OD_PERSIST_COMM.x1006_communicationCyclePeriod,
                                        .attribute  = ODA_SDO_RW | ODA_MB,
                                        .dataLength = 4},
    .o_1007_synchronousWindowLength  = {.dataOrig   = &OD_PERSIST_COMM.x1007_synchronousWindowLength,
                                        .attribute  = ODA_SDO_RW | ODA_MB,
                                        .dataLength = 4},
    .o_1008_manufacturerDeviceName = {.dataOrig  = &OD_PERSIST_COMM.x1008_manufacturerDeviceName[0],
                                      .attribute = ODA_SDO_R | ODA_STR,
                                      .dataLength = 4},
    .o_1009_manufacturerHardwareVersion =
        {.dataOrig   = &OD_PERSIST_COMM.x1009_manufacturerHardwareVersion[0],
         .attribute  = ODA_SDO_R | ODA_STR,
         .dataLength = 1},
    .o_1010_storeParameters          = {.dataOrig0         = &OD_RAM.x1010_storeParameters_sub0,
                                        .dataOrig          = &OD_RAM.x1010_storeParameters[0],
                                        .attribute0        = ODA_SDO_R,
                                        .attribute         = ODA_SDO_RW | ODA_MB,
                                        .dataElementLength = 4,
                                        .dataElementSizeof = sizeof(uint32_t)},
    .o_1011_restoreDefaultParameters = {.dataOrig0  = &OD_RAM.x1011_restoreDefaultParameters_sub0,
                                        .dataOrig   = &OD_RAM.x1011_restoreDefaultParameters[0],
                                        .attribute0 = ODA_SDO_R,
                                        .attribute  = ODA_SDO_RW | ODA_MB,
                                        .dataElementLength = 4,
                                        .dataElementSizeof = sizeof(uint32_t)},
    .o_1012_COB_IDTimeStampObject    = {.dataOrig   = &OD_PERSIST_COMM.x1012_COB_IDTimeStampObject,
                                        .attribute  = ODA_SDO_RW | ODA_MB,
                                        .dataLength = 4},
    .o_1014_COB_ID_EMCY              = {.dataOrig   = &OD_PERSIST_COMM.x1014_COB_ID_EMCY,
                                        .attribute  = ODA_SDO_RW | ODA_MB,
                                        .dataLength = 4},
    .o_1015_inhibitTimeEMCY          = {.dataOrig   = &OD_PERSIST_COMM.x1015_inhibitTimeEMCY,
                                        .attribute  = ODA_SDO_RW | ODA_MB,
                                        .dataLength = 2},
    .o_1016_consumerHeartbeatTime = {.dataOrig0 = &OD_PERSIST_COMM.x1016_consumerHeartbeatTime_sub0,
                                     .dataOrig  = &OD_PERSIST_COMM.x1016_consumerHeartbeatTime[0],
                                     .attribute0        = ODA_SDO_R,
                                     .attribute         = ODA_SDO_RW | ODA_MB,
                                     .dataElementLength = 4,
                                     .dataElementSizeof = sizeof(uint32_t)},
    .o_1017_producerHeartbeatTime = {.dataOrig   = &OD_PERSIST_COMM.x1017_producerHeartbeatTime,
                                     .attribute  = ODA_SDO_RW | ODA_MB,
                                     .dataLength = 2},
    .o_1018_identity = {{.dataOrig   = &OD_PERSIST_COMM.x1018_identity.highestSub_indexSupported,
                         .subIndex   = 0,
                         .attribute  = ODA_SDO_R,
                         .dataLength = 1},
                        {.dataOrig   = &OD_PERSIST_COMM.x1018_identity.vendor_ID,
                         .subIndex   = 1,
                         .attribute  = ODA_SDO_R | ODA_MB,
                         .dataLength = 4},
                        {.dataOrig   = &OD_PERSIST_COMM.x1018_identity.productCode,
                         .subIndex   = 2,
                         .attribute  = ODA_SDO_R | ODA_MB,
                         .dataLength = 4},
                        {.dataOrig   = &OD_PERSIST_COMM.x1018_identity.revisionNumber,
                         .subIndex   = 3,
                         .attribute  = ODA_SDO_R | ODA_MB,
                         .dataLength = 4},
                        {.dataOrig   = &OD_PERSIST_COMM.x1018_identity.serialNumber,
                         .subIndex   = 4,
                         .attribute  = ODA_SDO_R | ODA_MB,
                         .dataLength = 4}},
    .o_1019_synchronousCounterOverflowValue =
        {.dataOrig   = &OD_PERSIST_COMM.x1019_synchronousCounterOverflowValue,
         .attribute  = ODA_SDO_RW,
         .dataLength = 1},
    .o_1200_SDOServerParameter =
        {{.dataOrig   = &OD_RAM.x1200_SDOServerParameter.highestSub_indexSupported,
          .subIndex   = 0,
          .attribute  = ODA_SDO_R,
          .dataLength = 1},
         {.dataOrig   = &OD_RAM.x1200_SDOServerParameter.COB_IDClientToServerRx,
          .subIndex   = 1,
          .attribute  = ODA_SDO_R | ODA_TRPDO | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_RAM.x1200_SDOServerParameter.COB_IDServerToClientTx,
          .subIndex   = 2,
          .attribute  = ODA_SDO_R | ODA_TRPDO | ODA_MB,
          .dataLength = 4}},
    .o_1201_SDOServerParameter =
        {{.dataOrig   = &OD_RAM.x1201_SDOServerParameter.highestSub_indexSupported,
          .subIndex   = 0,
          .attribute  = ODA_SDO_R,
          .dataLength = 1},
         {.dataOrig   = &OD_RAM.x1201_SDOServerParameter.COB_IDClientToServerRx,
          .subIndex   = 1,
          .attribute  = ODA_SDO_R | ODA_TRPDO | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_RAM.x1201_SDOServerParameter.COB_IDServerToClientTx,
          .subIndex   = 2,
          .attribute  = ODA_SDO_R | ODA_TRPDO | ODA_MB,
          .dataLength = 4}},
    .o_1280_SDOClientParameter =
        {{.dataOrig   = &OD_PERSIST_COMM.x1280_SDOClientParameter.highestSub_indexSupported,
          .subIndex   = 0,
          .attribute  = ODA_SDO_R,
          .dataLength = 1},
         {.dataOrig   = &OD_PERSIST_COMM.x1280_SDOClientParameter.COB_IDClientToServerTx,
          .subIndex   = 1,
          .attribute  = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1280_SDOClientParameter.COB_IDServerToClientRx,
          .subIndex   = 2,
          .attribute  = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1280_SDOClientParameter.node_IDOfTheSDOServer,
          .subIndex   = 3,
          .attribute  = ODA_SDO_RW,
          .dataLength = 1}},
    .o_1400_RPDOCommunicationParameter =
        {{.dataOrig   = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.maxSub_index,
          .subIndex   = 0,
          .attribute  = ODA_SDO_R,
          .dataLength = 1},
         {.dataOrig   = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.COB_IDUsedByRPDO,
          .subIndex   = 1,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.transmissionType,
          .subIndex   = 2,
          .attribute  = ODA_SDO_RW,
          .dataLength = 1}},
    .o_1401_RPDOCommunicationParameter =
        {{.dataOrig   = &OD_PERSIST_COMM.x1401_RPDOCommunicationParameter.maxSub_index,
          .subIndex   = 0,
          .attribute  = ODA_SDO_R,
          .dataLength = 1},
         {.dataOrig   = &OD_PERSIST_COMM.x1401_RPDOCommunicationParameter.COB_IDUsedByRPDO,
          .subIndex   = 1,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1401_RPDOCommunicationParameter.transmissionType,
          .subIndex   = 2,
          .attribute  = ODA_SDO_RW,
          .dataLength = 1}},
    .o_1402_RPDOCommunicationParameter =
        {{.dataOrig   = &OD_PERSIST_COMM.x1402_RPDOCommunicationParameter.maxSub_index,
          .subIndex   = 0,
          .attribute  = ODA_SDO_R,
          .dataLength = 1},
         {.dataOrig   = &OD_PERSIST_COMM.x1402_RPDOCommunicationParameter.COB_IDUsedByRPDO,
          .subIndex   = 1,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1402_RPDOCommunicationParameter.transmissionType,
          .subIndex   = 2,
          .attribute  = ODA_SDO_RW,
          .dataLength = 1}},
    .o_1403_RPDOCommunicationParameter =
        {{.dataOrig   = &OD_PERSIST_COMM.x1403_RPDOCommunicationParameter.maxSub_index,
          .subIndex   = 0,
          .attribute  = ODA_SDO_R,
          .dataLength = 1},
         {.dataOrig   = &OD_PERSIST_COMM.x1403_RPDOCommunicationParameter.COB_IDUsedByRPDO,
          .subIndex   = 1,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1403_RPDOCommunicationParameter.transmissionType,
          .subIndex   = 2,
          .attribute  = ODA_SDO_RW,
          .dataLength = 1}},
    .o_1600_RPDOMappingParameter =
        {{.dataOrig   = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.numberOfMappedObjects,
          .subIndex   = 0,
          .attribute  = ODA_SDO_RW,
          .dataLength = 1},
         {.dataOrig   = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.mappedObject_1,
          .subIndex   = 1,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.mappedObject_2,
          .subIndex   = 2,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.mappedObject_3,
          .subIndex   = 3,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.mappedObject_4,
          .subIndex   = 4,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.mappedObject_5,
          .subIndex   = 5,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.mappedObject_6,
          .subIndex   = 6,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.mappedObject_7,
          .subIndex   = 7,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.mappedObject_8,
          .subIndex   = 8,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4}},
    .o_1601_RPDOMappingParameter =
        {{.dataOrig   = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.numberOfMappedObjects,
          .subIndex   = 0,
          .attribute  = ODA_SDO_RW,
          .dataLength = 1},
         {.dataOrig   = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.mappedObject_1,
          .subIndex   = 1,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.mappedObject_2,
          .subIndex   = 2,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.mappedObject_3,
          .subIndex   = 3,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.mappedObject_4,
          .subIndex   = 4,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.mappedObject_5,
          .subIndex   = 5,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.mappedObject_6,
          .subIndex   = 6,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.mappedObject_7,
          .subIndex   = 7,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.mappedObject_8,
          .subIndex   = 8,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4}},
    .o_1602_RPDOMappingParameter =
        {{.dataOrig   = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.numberOfMappedObjects,
          .subIndex   = 0,
          .attribute  = ODA_SDO_RW,
          .dataLength = 1},
         {.dataOrig   = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.mappedObject_1,
          .subIndex   = 1,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.mappedObject_2,
          .subIndex   = 2,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.mappedObject_3,
          .subIndex   = 3,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.mappedObject_4,
          .subIndex   = 4,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.mappedObject_5,
          .subIndex   = 5,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.mappedObject_6,
          .subIndex   = 6,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.mappedObject_7,
          .subIndex   = 7,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.mappedObject_8,
          .subIndex   = 8,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4}},
    .o_1603_RPDOMappingParameter =
        {{.dataOrig   = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.numberOfMappedObjects,
          .subIndex   = 0,
          .attribute  = ODA_SDO_RW,
          .dataLength = 1},
         {.dataOrig   = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.mappedObject_1,
          .subIndex   = 1,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.mappedObject_2,
          .subIndex   = 2,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.mappedObject_3,
          .subIndex   = 3,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.mappedObject_4,
          .subIndex   = 4,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.mappedObject_5,
          .subIndex   = 5,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.mappedObject_6,
          .subIndex   = 6,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.mappedObject_7,
          .subIndex   = 7,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.mappedObject_8,
          .subIndex   = 8,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4}},
    .o_1800_TPDOCommunicationParameter =
        {{.dataOrig   = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.maxSub_index,
          .subIndex   = 0,
          .attribute  = ODA_SDO_R,
          .dataLength = 1},
         {.dataOrig   = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.COB_IDUsedByTPDO,
          .subIndex   = 1,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.transmissionType,
          .subIndex   = 2,
          .attribute  = ODA_SDO_RW,
          .dataLength = 1},
         {.dataOrig   = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.inhibitTime,
          .subIndex   = 3,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 2},
         {.dataOrig   = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.compatibilityEntry,
          .subIndex   = 4,
          .attribute  = ODA_SDO_RW,
          .dataLength = 1},
         {.dataOrig   = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.eventTimer,
          .subIndex   = 5,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 2},
         {.dataOrig   = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.SYNCStartValue,
          .subIndex   = 6,
          .attribute  = ODA_SDO_RW,
          .dataLength = 1}},
    .o_1801_TPDOCommunicationParameter =
        {{.dataOrig   = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.maxSub_index,
          .subIndex   = 0,
          .attribute  = ODA_SDO_R,
          .dataLength = 1},
         {.dataOrig   = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.COB_IDUsedByTPDO,
          .subIndex   = 1,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.transmissionType,
          .subIndex   = 2,
          .attribute  = ODA_SDO_RW,
          .dataLength = 1},
         {.dataOrig   = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.inhibitTime,
          .subIndex   = 3,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 2},
         {.dataOrig   = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.compatibilityEntry,
          .subIndex   = 4,
          .attribute  = ODA_SDO_RW,
          .dataLength = 1},
         {.dataOrig   = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.eventTimer,
          .subIndex   = 5,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 2},
         {.dataOrig   = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.SYNCStartValue,
          .subIndex   = 6,
          .attribute  = ODA_SDO_RW,
          .dataLength = 1}},
    .o_1802_TPDOCommunicationParameter =
        {{.dataOrig   = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.maxSub_index,
          .subIndex   = 0,
          .attribute  = ODA_SDO_R,
          .dataLength = 1},
         {.dataOrig   = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.COB_IDUsedByTPDO,
          .subIndex   = 1,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.transmissionType,
          .subIndex   = 2,
          .attribute  = ODA_SDO_RW,
          .dataLength = 1},
         {.dataOrig   = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.inhibitTime,
          .subIndex   = 3,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 2},
         {.dataOrig   = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.compatibilityEntry,
          .subIndex   = 4,
          .attribute  = ODA_SDO_RW,
          .dataLength = 1},
         {.dataOrig   = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.eventTimer,
          .subIndex   = 5,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 2},
         {.dataOrig   = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.SYNCStartValue,
          .subIndex   = 6,
          .attribute  = ODA_SDO_RW,
          .dataLength = 1}},
    .o_1803_TPDOCommunicationParameter =
        {{.dataOrig   = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.maxSub_index,
          .subIndex   = 0,
          .attribute  = ODA_SDO_R,
          .dataLength = 1},
         {.dataOrig   = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.COB_IDUsedByTPDO,
          .subIndex   = 1,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.transmissionType,
          .subIndex   = 2,
          .attribute  = ODA_SDO_RW,
          .dataLength = 1},
         {.dataOrig   = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.inhibitTime,
          .subIndex   = 3,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 2},
         {.dataOrig   = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.compatibilityEntry,
          .subIndex   = 4,
          .attribute  = ODA_SDO_RW,
          .dataLength = 1},
         {.dataOrig   = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.eventTimer,
          .subIndex   = 5,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 2},
         {.dataOrig   = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.SYNCStartValue,
          .subIndex   = 6,
          .attribute  = ODA_SDO_RW,
          .dataLength = 1}},
    .o_1A00_TPDOMappingParameter =
        {{.dataOrig   = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.numberOfMappedObjects,
          .subIndex   = 0,
          .attribute  = ODA_SDO_RW,
          .dataLength = 1},
         {.dataOrig   = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.mappedObject_1,
          .subIndex   = 1,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.mappedObject_2,
          .subIndex   = 2,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4}},
    .o_1A01_TPDOMappingParameter =
        {{.dataOrig   = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.numberOfMappedObjects,
          .subIndex   = 0,
          .attribute  = ODA_SDO_RW,
          .dataLength = 1},
         {.dataOrig   = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.mappedObject_1,
          .subIndex   = 1,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.mappedObject_2,
          .subIndex   = 2,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4}},
    .o_1A02_TPDOMappingParameter =
        {{.dataOrig   = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.numberOfMappedObjects,
          .subIndex   = 0,
          .attribute  = ODA_SDO_RW,
          .dataLength = 1},
         {.dataOrig   = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.mappedObject_1,
          .subIndex   = 1,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.mappedObject_2,
          .subIndex   = 2,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4}},
    .o_1A03_TPDOMappingParameter =
        {{.dataOrig   = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.numberOfMappedObjects,
          .subIndex   = 0,
          .attribute  = ODA_SDO_RW,
          .dataLength = 1},
         {.dataOrig   = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.mappedObject_1,
          .subIndex   = 1,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.mappedObject_2,
          .subIndex   = 2,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4}},
    .o_2000_motorSettings = {{.dataOrig   = &OD_RAM.x2000_motorSettings.highestSub_indexSupported,
                              .subIndex   = 0,
                              .attribute  = ODA_SDO_R,
                              .dataLength = 1},
                             {.dataOrig   = &OD_RAM.x2000_motorSettings.polePairs,
                              .subIndex   = 1,
                              .attribute  = ODA_SDO_RW | ODA_MB,
                              .dataLength = 4},
                             {.dataOrig   = &OD_RAM.x2000_motorSettings.torqueConstant,
                              .subIndex   = 2,
                              .attribute  = ODA_SDO_RW | ODA_MB,
                              .dataLength = 4},
                             {.dataOrig   = &OD_RAM.x2000_motorSettings.phaseInductance,
                              .subIndex   = 3,
                              .attribute  = ODA_SDO_R | ODA_MB,
                              .dataLength = 4},
                             {.dataOrig   = &OD_RAM.x2000_motorSettings.phaseResistance,
                              .subIndex   = 4,
                              .attribute  = ODA_SDO_R | ODA_MB,
                              .dataLength = 4},
                             {.dataOrig   = &OD_RAM.x2000_motorSettings.torqueBandwidth,
                              .subIndex   = 5,
                              .attribute  = ODA_SDO_RW | ODA_MB,
                              .dataLength = 2},
                             {.dataOrig   = &OD_RAM.x2000_motorSettings.motorName[0],
                              .subIndex   = 6,
                              .attribute  = ODA_SDO_RW | ODA_STR,
                              .dataLength = 4},
                             {.dataOrig   = &OD_RAM.x2000_motorSettings.motorShutdownTemperature,
                              .subIndex   = 7,
                              .attribute  = ODA_SDO_RW,
                              .dataLength = 1},
                             {.dataOrig   = &OD_RAM.x2000_motorSettings.gearRatio,
                              .subIndex   = 8,
                              .attribute  = ODA_SDO_RW | ODA_MB,
                              .dataLength = 4},
                             {.dataOrig   = &OD_RAM.x2000_motorSettings.calibrationMode,
                              .subIndex   = 9,
                              .attribute  = ODA_SDO_RW,
                              .dataLength = 1},
                             {.dataOrig   = &OD_RAM.x2000_motorSettings.canID,
                              .subIndex   = 10,
                              .attribute  = ODA_SDO_RW | ODA_MB,
                              .dataLength = 4},
                             {.dataOrig   = &OD_RAM.x2000_motorSettings.canBaudrate,
                              .subIndex   = 11,
                              .attribute  = ODA_SDO_RW | ODA_MB,
                              .dataLength = 4},
                             {.dataOrig   = &OD_RAM.x2000_motorSettings.canWatchdog,
                              .subIndex   = 12,
                              .attribute  = ODA_SDO_RW | ODA_MB,
                              .dataLength = 2},
                             {.dataOrig   = &OD_RAM.x2000_motorSettings.reverseDirection,
                              .subIndex   = 13,
                              .attribute  = ODA_SDO_RW,
                              .dataLength = 1}},
    .o_2001_velocityPID_Controller =
        {{.dataOrig   = &OD_RAM.x2001_velocityPID_Controller.highestSub_indexSupported,
          .subIndex   = 0,
          .attribute  = ODA_SDO_R,
          .dataLength = 1},
         {.dataOrig   = &OD_RAM.x2001_velocityPID_Controller.kp,
          .subIndex   = 1,
          .attribute  = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_RAM.x2001_velocityPID_Controller.ki,
          .subIndex   = 2,
          .attribute  = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_RAM.x2001_velocityPID_Controller.kd,
          .subIndex   = 3,
          .attribute  = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_RAM.x2001_velocityPID_Controller.integralLimit,
          .subIndex   = 4,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4}},
    .o_2002_positionPID_Controller =
        {{.dataOrig   = &OD_RAM.x2002_positionPID_Controller.highestSub_indexSupported,
          .subIndex   = 0,
          .attribute  = ODA_SDO_R,
          .dataLength = 1},
         {.dataOrig   = &OD_RAM.x2002_positionPID_Controller.kp,
          .subIndex   = 1,
          .attribute  = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_RAM.x2002_positionPID_Controller.ki,
          .subIndex   = 2,
          .attribute  = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_RAM.x2002_positionPID_Controller.kd,
          .subIndex   = 3,
          .attribute  = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_RAM.x2002_positionPID_Controller.integralLimit,
          .subIndex   = 4,
          .attribute  = ODA_SDO_RW | ODA_MB,
          .dataLength = 4}},
    .o_2003_systemCommand    = {{.dataOrig   = &OD_RAM.x2003_systemCommand.highestSub_indexSupported,
                                 .subIndex   = 0,
                                 .attribute  = ODA_SDO_R,
                                 .dataLength = 1},
                                {.dataOrig   = &OD_RAM.x2003_systemCommand.blinkLEDs,
                                 .subIndex   = 1,
                                 .attribute  = ODA_SDO_RW,
                                 .dataLength = 1},
                                {.dataOrig   = &OD_RAM.x2003_systemCommand.resetController,
                                 .subIndex   = 2,
                                 .attribute  = ODA_SDO_RW,
                                 .dataLength = 1},
                                {.dataOrig   = &OD_RAM.x2003_systemCommand.runCalibration,
                                 .subIndex   = 3,
                                 .attribute  = ODA_SDO_RW,
                                 .dataLength = 1},
                                {.dataOrig   = &OD_RAM.x2003_systemCommand.runOutputEncoderCalibration,
                                 .subIndex   = 4,
                                 .attribute  = ODA_SDO_RW,
                                 .dataLength = 1},
                                {.dataOrig   = &OD_RAM.x2003_systemCommand.setZero,
                                 .subIndex   = 5,
                                 .attribute  = ODA_SDO_RW,
                                 .dataLength = 1},
                                {.dataOrig   = &OD_RAM.x2003_systemCommand.calibrateCurrentPI_Gains,
                                 .subIndex   = 6,
                                 .attribute  = ODA_SDO_RW,
                                 .dataLength = 1},
                                {.dataOrig   = &OD_RAM.x2003_systemCommand.testOutputEncoder,
                                 .subIndex   = 7,
                                 .attribute  = ODA_SDO_RW,
                                 .dataLength = 1},
                                {.dataOrig   = &OD_RAM.x2003_systemCommand.testMainEncoder,
                                 .subIndex   = 8,
                                 .attribute  = ODA_SDO_RW,
                                 .dataLength = 1},
                                {.dataOrig   = &OD_RAM.x2003_systemCommand.saveMemory,
                                 .subIndex   = 9,
                                 .attribute  = ODA_SDO_RW,
                                 .dataLength = 1},
                                {.dataOrig   = &OD_RAM.x2003_systemCommand.revertFactorySettings,
                                 .subIndex   = 10,
                                 .attribute  = ODA_SDO_RW,
                                 .dataLength = 1},
                                {.dataOrig   = &OD_RAM.x2003_systemCommand.clearErrors,
                                 .subIndex   = 11,
                                 .attribute  = ODA_SDO_RW,
                                 .dataLength = 1},
                                {.dataOrig   = &OD_RAM.x2003_systemCommand.clearWarnings,
                                 .subIndex   = 12,
                                 .attribute  = ODA_SDO_RW,
                                 .dataLength = 1},
                                {.dataOrig   = &OD_RAM.x2003_systemCommand.runCanReinit,
                                 .subIndex   = 13,
                                 .attribute  = ODA_SDO_RW,
                                 .dataLength = 1}},
    .o_2004_systemStatus     = {{.dataOrig   = &OD_RAM.x2004_systemStatus.highestSub_indexSupported,
                                 .subIndex   = 0,
                                 .attribute  = ODA_SDO_R,
                                 .dataLength = 1},
                                {.dataOrig   = &OD_RAM.x2004_systemStatus.mainEncoderStatus,
                                 .subIndex   = 1,
                                 .attribute  = ODA_SDO_RW | ODA_MB,
                                 .dataLength = 4},
                                {.dataOrig   = &OD_RAM.x2004_systemStatus.outputEncoderStatus,
                                 .subIndex   = 2,
                                 .attribute  = ODA_SDO_RW | ODA_MB,
                                 .dataLength = 4},
                                {.dataOrig   = &OD_RAM.x2004_systemStatus.calibrationStatus,
                                 .subIndex   = 3,
                                 .attribute  = ODA_SDO_RW | ODA_MB,
                                 .dataLength = 4},
                                {.dataOrig   = &OD_RAM.x2004_systemStatus.bridgeStatus,
                                 .subIndex   = 4,
                                 .attribute  = ODA_SDO_RW | ODA_MB,
                                 .dataLength = 4},
                                {.dataOrig   = &OD_RAM.x2004_systemStatus.hardwareStatus,
                                 .subIndex   = 5,
                                 .attribute  = ODA_SDO_RW | ODA_MB,
                                 .dataLength = 4},
                                {.dataOrig   = &OD_RAM.x2004_systemStatus.homingStatus,
                                 .subIndex   = 6,
                                 .attribute  = ODA_SDO_RW | ODA_MB,
                                 .dataLength = 4},
                                {.dataOrig   = &OD_RAM.x2004_systemStatus.motionStatus,
                                 .subIndex   = 7,
                                 .attribute  = ODA_SDO_RW | ODA_MB,
                                 .dataLength = 4},
                                {.dataOrig   = &OD_RAM.x2004_systemStatus.communicationStatus,
                                 .subIndex   = 8,
                                 .attribute  = ODA_SDO_RW | ODA_MB,
                                 .dataLength = 4}},
    .o_2005_outputEncoder    = {{.dataOrig   = &OD_RAM.x2005_outputEncoder.highestSub_indexSupported,
                                 .subIndex   = 0,
                                 .attribute  = ODA_SDO_R,
                                 .dataLength = 1},
                                {.dataOrig   = &OD_RAM.x2005_outputEncoder.type,
                                 .subIndex   = 1,
                                 .attribute  = ODA_SDO_RW,
                                 .dataLength = 1},
                                {.dataOrig   = &OD_RAM.x2005_outputEncoder.calibrationMode,
                                 .subIndex   = 2,
                                 .attribute  = ODA_SDO_RW,
                                 .dataLength = 1},
                                {.dataOrig   = &OD_RAM.x2005_outputEncoder.mode,
                                 .subIndex   = 3,
                                 .attribute  = ODA_SDO_RW,
                                 .dataLength = 1},
                                {.dataOrig   = &OD_RAM.x2005_outputEncoder.position,
                                 .subIndex   = 4,
                                 .attribute  = ODA_SDO_R | ODA_TRPDO | ODA_MB,
                                 .dataLength = 4},
                                {.dataOrig   = &OD_RAM.x2005_outputEncoder.velocity,
                                 .subIndex   = 5,
                                 .attribute  = ODA_SDO_RW | ODA_RPDO | ODA_MB,
                                 .dataLength = 4}},
    .o_2006_temperature      = {{.dataOrig   = &OD_RAM.x2006_temperature.highestSub_indexSupported,
                                 .subIndex   = 0,
                                 .attribute  = ODA_SDO_R,
                                 .dataLength = 1},
                                {.dataOrig   = &OD_RAM.x2006_temperature.motorTemperature,
                                 .subIndex   = 1,
                                 .attribute  = ODA_SDO_R | ODA_TRPDO | ODA_MB,
                                 .dataLength = 4},
                                {.dataOrig   = &OD_RAM.x2006_temperature.mosfetTemperature,
                                 .subIndex   = 2,
                                 .attribute  = ODA_SDO_R | ODA_TRPDO | ODA_MB,
                                 .dataLength = 4}},
    .o_2007_limits           = {{.dataOrig   = &OD_RAM.x2007_limits.highestSub_indexSupported,
                                 .subIndex   = 0,
                                 .attribute  = ODA_SDO_R,
                                 .dataLength = 1},
                                {.dataOrig   = &OD_RAM.x2007_limits.maxTorque,
                                 .subIndex   = 1,
                                 .attribute  = ODA_SDO_RW | ODA_MB,
                                 .dataLength = 4},
                                {.dataOrig   = &OD_RAM.x2007_limits.maxAcceleration,
                                 .subIndex   = 2,
                                 .attribute  = ODA_SDO_RW | ODA_MB,
                                 .dataLength = 4},
                                {.dataOrig   = &OD_RAM.x2007_limits.maxDeceleration,
                                 .subIndex   = 3,
                                 .attribute  = ODA_SDO_RW | ODA_MB,
                                 .dataLength = 4},
                                {.dataOrig   = &OD_RAM.x2007_limits.maxVelocity,
                                 .subIndex   = 4,
                                 .attribute  = ODA_SDO_RW | ODA_MB,
                                 .dataLength = 4},
                                {.dataOrig   = &OD_RAM.x2007_limits.maxPosition,
                                 .subIndex   = 5,
                                 .attribute  = ODA_SDO_RW | ODA_MB,
                                 .dataLength = 4},
                                {.dataOrig   = &OD_RAM.x2007_limits.minPosition,
                                 .subIndex   = 6,
                                 .attribute  = ODA_SDO_RW | ODA_MB,
                                 .dataLength = 4}},
    .o_2008_motion           = {{.dataOrig   = &OD_RAM.x2008_motion.highestSub_indexSupported,
                                 .subIndex   = 0,
                                 .attribute  = ODA_SDO_R,
                                 .dataLength = 1},
                                {.dataOrig   = &OD_RAM.x2008_motion.modeCommand,
                                 .subIndex   = 1,
                                 .attribute  = ODA_SDO_RW | ODA_TPDO,
                                 .dataLength = 1},
                                {.dataOrig   = &OD_RAM.x2008_motion.modeStatus,
                                 .subIndex   = 2,
                                 .attribute  = ODA_SDO_RW | ODA_TPDO,
                                 .dataLength = 1},
                                {.dataOrig   = &OD_RAM.x2008_motion.profileVelocity,
                                 .subIndex   = 3,
                                 .attribute  = ODA_SDO_RW | ODA_TPDO | ODA_MB,
                                 .dataLength = 4},
                                {.dataOrig   = &OD_RAM.x2008_motion.profileAcceleration,
                                 .subIndex   = 4,
                                 .attribute  = ODA_SDO_RW | ODA_TPDO | ODA_MB,
                                 .dataLength = 4},
                                {.dataOrig   = &OD_RAM.x2008_motion.profileDeceleration,
                                 .subIndex   = 5,
                                 .attribute  = ODA_SDO_RW | ODA_TPDO | ODA_MB,
                                 .dataLength = 4},
                                {.dataOrig   = &OD_RAM.x2008_motion.quickStopDeceleration,
                                 .subIndex   = 6,
                                 .attribute  = ODA_SDO_RW | ODA_TPDO | ODA_MB,
                                 .dataLength = 4},
                                {.dataOrig   = &OD_RAM.x2008_motion.positionWindow,
                                 .subIndex   = 7,
                                 .attribute  = ODA_SDO_RW | ODA_TPDO | ODA_MB,
                                 .dataLength = 4},
                                {.dataOrig   = &OD_RAM.x2008_motion.velocityWindow,
                                 .subIndex   = 8,
                                 .attribute  = ODA_SDO_RW | ODA_TPDO | ODA_MB,
                                 .dataLength = 4},
                                {.dataOrig   = &OD_RAM.x2008_motion.targetPosition,
                                 .subIndex   = 9,
                                 .attribute  = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
                                 .dataLength = 4},
                                {.dataOrig   = &OD_RAM.x2008_motion.targetVelocity,
                                 .subIndex   = 10,
                                 .attribute  = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
                                 .dataLength = 4},
                                {.dataOrig   = &OD_RAM.x2008_motion.targetTorque,
                                 .subIndex   = 11,
                                 .attribute  = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
                                 .dataLength = 4}},
    .o_2009_motorMesurements = {{.dataOrig =
                                     &OD_RAM.x2009_motorMesurements.highestSub_indexSupported,
                                 .subIndex   = 0,
                                 .attribute  = ODA_SDO_R,
                                 .dataLength = 1},
                                {.dataOrig   = &OD_RAM.x2009_motorMesurements.outputPosition,
                                 .subIndex   = 1,
                                 .attribute  = ODA_SDO_RW | ODA_RPDO | ODA_MB,
                                 .dataLength = 4},
                                {.dataOrig   = &OD_RAM.x2009_motorMesurements.outputVelocity,
                                 .subIndex   = 2,
                                 .attribute  = ODA_SDO_RW | ODA_RPDO | ODA_MB,
                                 .dataLength = 4},
                                {.dataOrig   = &OD_RAM.x2009_motorMesurements.outputTorque,
                                 .subIndex   = 3,
                                 .attribute  = ODA_SDO_RW | ODA_RPDO | ODA_MB,
                                 .dataLength = 4}},
    .o_200A_firmwareInfo     = {{.dataOrig   = &OD_RAM.x200A_firmwareInfo.highestSub_indexSupported,
                                 .subIndex   = 0,
                                 .attribute  = ODA_SDO_R,
                                 .dataLength = 1},
                                {.dataOrig   = &OD_RAM.x200A_firmwareInfo.commitHash[0],
                                 .subIndex   = 1,
                                 .attribute  = ODA_SDO_R | ODA_STR,
                                 .dataLength = 1},
                                {.dataOrig   = &OD_RAM.x200A_firmwareInfo.buildDate,
                                 .subIndex   = 2,
                                 .attribute  = ODA_SDO_R | ODA_MB,
                                 .dataLength = 4},
                                {.dataOrig   = &OD_RAM.x200A_firmwareInfo.version,
                                 .subIndex   = 3,
                                 .attribute  = ODA_SDO_R | ODA_MB,
                                 .dataLength = 4}},
    .o_200B_bootloderInfo    = {{.dataOrig   = &OD_RAM.x200B_bootloderInfo.highestSub_indexSupported,
                                 .subIndex   = 0,
                                 .attribute  = ODA_SDO_R,
                                 .dataLength = 1},
                                {.dataOrig   = &OD_RAM.x200B_bootloderInfo.bootloaderFixed,
                                 .subIndex   = 1,
                                 .attribute  = ODA_SDO_R,
                                 .dataLength = 1},
                                {.dataOrig   = &OD_RAM.x200B_bootloderInfo.commitHash[0],
                                 .subIndex   = 2,
                                 .attribute  = ODA_SDO_R | ODA_STR,
                                 .dataLength = 1},
                                {.dataOrig   = &OD_RAM.x200B_bootloderInfo.buildDate,
                                 .subIndex   = 3,
                                 .attribute  = ODA_SDO_R | ODA_MB,
                                 .dataLength = 4},
                                {.dataOrig   = &OD_RAM.x200B_bootloderInfo.version,
                                 .subIndex   = 4,
                                 .attribute  = ODA_SDO_R | ODA_MB,
                                 .dataLength = 4}},
    .o_200C_impedancePD_Controller =
        {{.dataOrig   = &OD_RAM.x200C_impedancePD_Controller.highestSub_indexSupported,
          .subIndex   = 0,
          .attribute  = ODA_SDO_R,
          .dataLength = 1},
         {.dataOrig   = &OD_RAM.x200C_impedancePD_Controller.kp,
          .subIndex   = 1,
          .attribute  = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_RAM.x200C_impedancePD_Controller.kd,
          .subIndex   = 2,
          .attribute  = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
          .dataLength = 4}},
    .o_200D_userGPIO         = {{.dataOrig   = &OD_RAM.x200D_userGPIO.highestSub_indexSupported,
                                 .subIndex   = 0,
                                 .attribute  = ODA_SDO_R,
                                 .dataLength = 1},
                                {.dataOrig   = &OD_RAM.x200D_userGPIO.userGPIO_Configuration,
                                 .subIndex   = 1,
                                 .attribute  = ODA_SDO_RW,
                                 .dataLength = 1},
                                {.dataOrig   = &OD_RAM.x200D_userGPIO.userGPIO_State,
                                 .subIndex   = 2,
                                 .attribute  = ODA_SDO_R | ODA_MB,
                                 .dataLength = 2}},
    .o_200E_DCBusVoltage     = {.dataOrig   = &OD_RAM.x200E_DCBusVoltage,
                                .attribute  = ODA_SDO_R | ODA_MB,
                                .dataLength = 4},
    .o_6040_controlword      = {.dataOrig   = &OD_RAM.x6040_controlword,
                                .attribute  = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
                                .dataLength = 2},
    .o_6041_statusword       = {.dataOrig   = &OD_RAM.x6041_statusword,
                                .attribute  = ODA_SDO_R | ODA_TRPDO | ODA_MB,
                                .dataLength = 2},
    .o_6060_modesOfOperation = {.dataOrig   = &OD_RAM.x6060_modesOfOperation,
                                .attribute  = ODA_SDO_RW | ODA_RPDO,
                                .dataLength = 1},
    .o_6061_modesOfOperationDisplay = {.dataOrig   = &OD_RAM.x6061_modesOfOperationDisplay,
                                       .attribute  = ODA_SDO_R | ODA_TRPDO,
                                       .dataLength = 1},
    .o_6062_positionDemandValue     = {.dataOrig   = &OD_RAM.x6062_positionDemandValue,
                                       .attribute  = ODA_SDO_R | ODA_MB,
                                       .dataLength = 4},
    .o_6064_positionValue           = {.dataOrig   = &OD_RAM.x6064_positionValue,
                                       .attribute  = ODA_SDO_R | ODA_TRPDO | ODA_MB,
                                       .dataLength = 4},
    .o_6067_positionWindow          = {.dataOrig   = &OD_RAM.x6067_positionWindow,
                                       .attribute  = ODA_SDO_RW | ODA_MB,
                                       .dataLength = 4},
    .o_606B_velocityDemandValue     = {.dataOrig   = &OD_RAM.x606B_velocityDemandValue,
                                       .attribute  = ODA_SDO_RW | ODA_MB,
                                       .dataLength = 4},
    .o_606C_velocityActualValue     = {.dataOrig   = &OD_RAM.x606C_velocityActualValue,
                                       .attribute  = ODA_SDO_R | ODA_TRPDO | ODA_MB,
                                       .dataLength = 4},
    .o_606D_velocityWindow          = {.dataOrig   = &OD_RAM.x606D_velocityWindow,
                                       .attribute  = ODA_SDO_RW | ODA_MB,
                                       .dataLength = 4},
    .o_6072_maxTorque               = {.dataOrig   = &OD_RAM.x6072_maxTorque,
                                       .attribute  = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
                                       .dataLength = 2},
    .o_6073_maxCurrent              = {.dataOrig   = &OD_RAM.x6073_maxCurrent,
                                       .attribute  = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
                                       .dataLength = 2},
    .o_6074_torqueDemandValue       = {.dataOrig   = &OD_RAM.x6074_torqueDemandValue,
                                       .attribute  = ODA_SDO_RW | ODA_MB,
                                       .dataLength = 2},
    .o_6075_motorRatedCurrent       = {.dataOrig   = &OD_RAM.x6075_motorRatedCurrent,
                                       .attribute  = ODA_SDO_RW | ODA_MB,
                                       .dataLength = 4},
    .o_6076_motorRatedTorque        = {.dataOrig   = &OD_RAM.x6076_motorRatedTorque,
                                       .attribute  = ODA_SDO_RW | ODA_MB,
                                       .dataLength = 4},
    .o_6077_torqueActualValue       = {.dataOrig   = &OD_RAM.x6077_torqueActualValue,
                                       .attribute  = ODA_SDO_R | ODA_TRPDO | ODA_MB,
                                       .dataLength = 2},
    .o_6079_DClinkCircuitVoltage    = {.dataOrig   = &OD_RAM.x6079_DClinkCircuitVoltage,
                                       .attribute  = ODA_SDO_R | ODA_TRPDO | ODA_MB,
                                       .dataLength = 4},
    .o_607A_targetPosition          = {.dataOrig   = &OD_RAM.x607A_targetPosition,
                                       .attribute  = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
                                       .dataLength = 4},
    .o_607D_softwarePositionLimit =
        {{.dataOrig   = &OD_RAM.x607D_softwarePositionLimit.highestSub_indexSupported,
          .subIndex   = 0,
          .attribute  = ODA_SDO_R,
          .dataLength = 1},
         {.dataOrig   = &OD_RAM.x607D_softwarePositionLimit.minPositionLimit,
          .subIndex   = 1,
          .attribute  = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
          .dataLength = 4},
         {.dataOrig   = &OD_RAM.x607D_softwarePositionLimit.maxPositionLimit,
          .subIndex   = 2,
          .attribute  = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
          .dataLength = 4}},
    .o_6080_maxMotorSpeed         = {.dataOrig   = &OD_RAM.x6080_maxMotorSpeed,
                                     .attribute  = ODA_SDO_RW | ODA_MB,
                                     .dataLength = 4},
    .o_6081_profileVelocity       = {.dataOrig   = &OD_RAM.x6081_profileVelocity,
                                     .attribute  = ODA_SDO_RW | ODA_RPDO | ODA_MB,
                                     .dataLength = 4},
    .o_6083_profileAcceleration   = {.dataOrig   = &OD_RAM.x6083_profileAcceleration,
                                     .attribute  = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
                                     .dataLength = 4},
    .o_6084_profileDeceleration   = {.dataOrig   = &OD_RAM.x6084_profileDeceleration,
                                     .attribute  = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
                                     .dataLength = 4},
    .o_6085_quickStopDeceleration = {.dataOrig   = &OD_RAM.x6085_quickStopDeceleration,
                                     .attribute  = ODA_SDO_RW | ODA_RPDO | ODA_MB,
                                     .dataLength = 4},
    .o_60C5_maxAcceleration       = {.dataOrig   = &OD_RAM.x60C5_maxAcceleration,
                                     .attribute  = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
                                     .dataLength = 4},
    .o_60C6_maxDeceleration       = {.dataOrig   = &OD_RAM.x60C6_maxDeceleration,
                                     .attribute  = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
                                     .dataLength = 4},
    .o_60FF_targetVelocity        = {.dataOrig   = &OD_RAM.x60FF_targetVelocity,
                                     .attribute  = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
                                     .dataLength = 4},
    .o_6502_supportedDriveModes   = {.dataOrig   = &OD_RAM.x6502_supportedDriveModes,
                                     .attribute  = ODA_SDO_R | ODA_MB,
                                     .dataLength = 4}};

/*******************************************************************************
    Object dictionary
*******************************************************************************/
OD_entry_t ODList[] = {
    {0x1000, 0x01, ODT_VAR, &ODObjs.o_1000_deviceType, NULL},
    {0x1001, 0x01, ODT_VAR, &ODObjs.o_1001_errorRegister, NULL},
    {0x1003, 0x11, ODT_ARR, &ODObjs.o_1003_pre_definedErrorField, NULL},
    {0x1005, 0x01, ODT_VAR, &ODObjs.o_1005_COB_ID_SYNCMessage, NULL},
    {0x1006, 0x01, ODT_VAR, &ODObjs.o_1006_communicationCyclePeriod, NULL},
    {0x1007, 0x01, ODT_VAR, &ODObjs.o_1007_synchronousWindowLength, NULL},
    {0x1008, 0x01, ODT_VAR, &ODObjs.o_1008_manufacturerDeviceName, NULL},
    {0x1009, 0x01, ODT_VAR, &ODObjs.o_1009_manufacturerHardwareVersion, NULL},
    {0x1010, 0x05, ODT_ARR, &ODObjs.o_1010_storeParameters, NULL},
    {0x1011, 0x05, ODT_ARR, &ODObjs.o_1011_restoreDefaultParameters, NULL},
    {0x1012, 0x01, ODT_VAR, &ODObjs.o_1012_COB_IDTimeStampObject, NULL},
    {0x1014, 0x01, ODT_VAR, &ODObjs.o_1014_COB_ID_EMCY, NULL},
    {0x1015, 0x01, ODT_VAR, &ODObjs.o_1015_inhibitTimeEMCY, NULL},
    {0x1016, 0x09, ODT_ARR, &ODObjs.o_1016_consumerHeartbeatTime, NULL},
    {0x1017, 0x01, ODT_VAR, &ODObjs.o_1017_producerHeartbeatTime, NULL},
    {0x1018, 0x05, ODT_REC, &ODObjs.o_1018_identity, NULL},
    {0x1019, 0x01, ODT_VAR, &ODObjs.o_1019_synchronousCounterOverflowValue, NULL},
    {0x1200, 0x03, ODT_REC, &ODObjs.o_1200_SDOServerParameter, NULL},
    {0x1201, 0x03, ODT_REC, &ODObjs.o_1201_SDOServerParameter, NULL},
    {0x1280, 0x04, ODT_REC, &ODObjs.o_1280_SDOClientParameter, NULL},
    {0x1400, 0x03, ODT_REC, &ODObjs.o_1400_RPDOCommunicationParameter, NULL},
    {0x1401, 0x03, ODT_REC, &ODObjs.o_1401_RPDOCommunicationParameter, NULL},
    {0x1402, 0x03, ODT_REC, &ODObjs.o_1402_RPDOCommunicationParameter, NULL},
    {0x1403, 0x03, ODT_REC, &ODObjs.o_1403_RPDOCommunicationParameter, NULL},
    {0x1600, 0x09, ODT_REC, &ODObjs.o_1600_RPDOMappingParameter, NULL},
    {0x1601, 0x09, ODT_REC, &ODObjs.o_1601_RPDOMappingParameter, NULL},
    {0x1602, 0x09, ODT_REC, &ODObjs.o_1602_RPDOMappingParameter, NULL},
    {0x1603, 0x09, ODT_REC, &ODObjs.o_1603_RPDOMappingParameter, NULL},
    {0x1800, 0x07, ODT_REC, &ODObjs.o_1800_TPDOCommunicationParameter, NULL},
    {0x1801, 0x07, ODT_REC, &ODObjs.o_1801_TPDOCommunicationParameter, NULL},
    {0x1802, 0x07, ODT_REC, &ODObjs.o_1802_TPDOCommunicationParameter, NULL},
    {0x1803, 0x07, ODT_REC, &ODObjs.o_1803_TPDOCommunicationParameter, NULL},
    {0x1A00, 0x03, ODT_REC, &ODObjs.o_1A00_TPDOMappingParameter, NULL},
    {0x1A01, 0x03, ODT_REC, &ODObjs.o_1A01_TPDOMappingParameter, NULL},
    {0x1A02, 0x03, ODT_REC, &ODObjs.o_1A02_TPDOMappingParameter, NULL},
    {0x1A03, 0x03, ODT_REC, &ODObjs.o_1A03_TPDOMappingParameter, NULL},
    {0x2000, 0x0E, ODT_REC, &ODObjs.o_2000_motorSettings, NULL},
    {0x2001, 0x05, ODT_REC, &ODObjs.o_2001_velocityPID_Controller, NULL},
    {0x2002, 0x05, ODT_REC, &ODObjs.o_2002_positionPID_Controller, NULL},
    {0x2003, 0x0E, ODT_REC, &ODObjs.o_2003_systemCommand, NULL},
    {0x2004, 0x09, ODT_REC, &ODObjs.o_2004_systemStatus, NULL},
    {0x2005, 0x06, ODT_REC, &ODObjs.o_2005_outputEncoder, NULL},
    {0x2006, 0x03, ODT_REC, &ODObjs.o_2006_temperature, NULL},
    {0x2007, 0x07, ODT_REC, &ODObjs.o_2007_limits, NULL},
    {0x2008, 0x0C, ODT_REC, &ODObjs.o_2008_motion, NULL},
    {0x2009, 0x04, ODT_REC, &ODObjs.o_2009_motorMesurements, NULL},
    {0x200A, 0x04, ODT_REC, &ODObjs.o_200A_firmwareInfo, NULL},
    {0x200B, 0x05, ODT_REC, &ODObjs.o_200B_bootloderInfo, NULL},
    {0x200C, 0x03, ODT_REC, &ODObjs.o_200C_impedancePD_Controller, NULL},
    {0x200D, 0x03, ODT_REC, &ODObjs.o_200D_userGPIO, NULL},
    {0x200E, 0x01, ODT_VAR, &ODObjs.o_200E_DCBusVoltage, NULL},
    {0x6040, 0x01, ODT_VAR, &ODObjs.o_6040_controlword, NULL},
    {0x6041, 0x01, ODT_VAR, &ODObjs.o_6041_statusword, NULL},
    {0x6060, 0x01, ODT_VAR, &ODObjs.o_6060_modesOfOperation, NULL},
    {0x6061, 0x01, ODT_VAR, &ODObjs.o_6061_modesOfOperationDisplay, NULL},
    {0x6062, 0x01, ODT_VAR, &ODObjs.o_6062_positionDemandValue, NULL},
    {0x6064, 0x01, ODT_VAR, &ODObjs.o_6064_positionValue, NULL},
    {0x6067, 0x01, ODT_VAR, &ODObjs.o_6067_positionWindow, NULL},
    {0x606B, 0x01, ODT_VAR, &ODObjs.o_606B_velocityDemandValue, NULL},
    {0x606C, 0x01, ODT_VAR, &ODObjs.o_606C_velocityActualValue, NULL},
    {0x606D, 0x01, ODT_VAR, &ODObjs.o_606D_velocityWindow, NULL},
    {0x6072, 0x01, ODT_VAR, &ODObjs.o_6072_maxTorque, NULL},
    {0x6073, 0x01, ODT_VAR, &ODObjs.o_6073_maxCurrent, NULL},
    {0x6074, 0x01, ODT_VAR, &ODObjs.o_6074_torqueDemandValue, NULL},
    {0x6075, 0x01, ODT_VAR, &ODObjs.o_6075_motorRatedCurrent, NULL},
    {0x6076, 0x01, ODT_VAR, &ODObjs.o_6076_motorRatedTorque, NULL},
    {0x6077, 0x01, ODT_VAR, &ODObjs.o_6077_torqueActualValue, NULL},
    {0x6079, 0x01, ODT_VAR, &ODObjs.o_6079_DClinkCircuitVoltage, NULL},
    {0x607A, 0x01, ODT_VAR, &ODObjs.o_607A_targetPosition, NULL},
    {0x607D, 0x03, ODT_REC, &ODObjs.o_607D_softwarePositionLimit, NULL},
    {0x6080, 0x01, ODT_VAR, &ODObjs.o_6080_maxMotorSpeed, NULL},
    {0x6081, 0x01, ODT_VAR, &ODObjs.o_6081_profileVelocity, NULL},
    {0x6083, 0x01, ODT_VAR, &ODObjs.o_6083_profileAcceleration, NULL},
    {0x6084, 0x01, ODT_VAR, &ODObjs.o_6084_profileDeceleration, NULL},
    {0x6085, 0x01, ODT_VAR, &ODObjs.o_6085_quickStopDeceleration, NULL},
    {0x60C5, 0x01, ODT_VAR, &ODObjs.o_60C5_maxAcceleration, NULL},
    {0x60C6, 0x01, ODT_VAR, &ODObjs.o_60C6_maxDeceleration, NULL},
    {0x60FF, 0x01, ODT_VAR, &ODObjs.o_60FF_targetVelocity, NULL},
    {0x6502, 0x01, ODT_VAR, &ODObjs.o_6502_supportedDriveModes, NULL},
    {0x0000, 0x00, 0, NULL, NULL}};

// static OD_t _OD = {(sizeof(ODList) / sizeof(ODList[0])) - 1, &ODList[0]};

// OD_t* OD = &_OD;
