set(CPACK_PROJECT_NAME "candlelib")
set(CPACK_PACKAGE_NAME candlelib)
set(CPACK_PACKAGE_FILE_NAME
    ${CPACK_PACKAGE_NAME}-${CANDLELIB_VERSION_FULL}-${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}
)
set(CPACK_PACKAGE_VERSION_MAJOR ${CANDLELIB_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${CANDLELIB_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${CANDLELIB_VERSION_PATCH})
set(CPACK_PACKAGE_VENDOR "MAB Robotics")
set(CPACK_PACKAGE_DESCRIPTION
    "Candle C++ Library")
set(CPACK_RESOURCE_FILE_LICENSE ${CMAKE_CURRENT_SOURCE_DIR}/LICENSE)
set(CPACK_RESOURCE_FILE_README ${CMAKE_CURRENT_SOURCE_DIR}/README.md)
set(CPACK_MONOLITHIC_INSTALL OFF)

if(WIN32)
    set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON)
    set(CPACK_NSIS_MODIFY_PATH OFF)
    set(CPACK_NSIS_MUI_ICON "${CMAKE_CURRENT_SOURCE_DIR}/MAB.ico")
    set(CPACK_NSIS_MUI_UNIICON "${CMAKE_CURRENT_SOURCE_DIR}/MAB.ico")
elseif(UNIX)
    set(CPACK_GENERATOR "DEB")
    set(CPACK_DEBIAN_PACKAGE_MAINTAINER "MAB Robotics <contact@mabrobotics.pl>")
    set(CPACK_DEBIAN_PACKAGE_DEPENDS libusb-1.0-0)
    set(CPACK_DEBIAN_PACKAGE_VERSION)

    if(${CMAKE_SYSTEM_PROCESSOR} STREQUAL "aarch64")
        set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "arm64")
    elseif(${CMAKE_SYSTEM_PROCESSOR} STREQUAL "armhf")
        set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "armhf")
    endif()

    message(CPACK_DEBIAN_PACKAGE_ARCHITECTURE =
        ${CPACK_DEBIAN_PACKAGE_ARCHITECTURE})
endif()

set(CPACK_COMPONENTS_ALL ${CANDLELIB_CPACK_COMPONENTS})
set(CPACK_INSTALL_CMAKE_PROJECTS)

foreach(_candlelib_component ${CANDLELIB_CPACK_COMPONENTS})
    list(APPEND CPACK_INSTALL_CMAKE_PROJECTS
        "${CMAKE_BINARY_DIR};${CMAKE_PROJECT_NAME};${_candlelib_component};/")
endforeach()

set(CPACK_OUTPUT_CONFIG_FILE "${CMAKE_BINARY_DIR}/CPackConfig_candlelib.cmake")
include(CPack)