#!/bin/bash

BUILD_DIRECTORY="buildWindows"

mkdir $BUILD_DIRECTORY
cd $BUILD_DIRECTORY
cmake -DPLATFORM="WIN" -DOPENSSL_ROOT_DIR="/usr/local/lib64/" -DOPENSSL_USE_STATIC_LIBS=TRUE ..
make -j4
cpack -G NSIS -DCPACK_INSTALL_CMAKE_PROJECTS=ALL