#!/bin/bash

BUILD_DIRECTORY="buildWindows"

rm -rf $BUILD_DIRECTORY
mkdir $BUILD_DIRECTORY
cd $BUILD_DIRECTORY
cmake -DPLATFORM="WIN" -DOPENSSL_ROOT_DIR="/usr/local/lib64/" -DOPENSSL_USE_STATIC_LIBS=TRUE ..
make -j4