# MAB Robotics CANDLE SDK GitHub Actions workflow file
name: CANDLE_SDK_CI

on:
  push:
    branches: [ "candletool", "github_workflows" ]
  pull_request:
    branches: [ "candletool" ]

jobs:
  build-candleSDK-linux:
    runs-on: ubuntu-22.04
    container:
      image: mabroboticsofficial/candlesdk_linux

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: CMake configure
      run: |
        cmake -B build -G "Unix Makefiles" .

    - name: Build
      run: cmake --build ./build

    - name: Create .deb package
      run: make -C ./build package