name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - CS-29-create-main-release-scripts # for testing

jobs:
  release:
    needs:
      - build-candleSDK-linux-static
      - build-candleSDK-linux-arm64-static
      - build-candleSDK-linux-armhf-static
      - build-candleSDK-windows-static
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Extract version from CMakeLists.txt
        id: extract_version
        run: |
          MAJOR=$(grep -Po 'set\(CANDLESDK_VERSION_1\s+\K[0-9]+' CMakeLists.txt)
          MINOR=$(grep -Po 'set\(CANDLESDK_VERSION_2\s+\K[0-9]+' CMakeLists.txt)
          PATCH=$(grep -Po 'set\(CANDLESDK_VERSION_3\s+\K[0-9]+' CMakeLists.txt)
          VERSION="$MAJOR.$MINOR.$PATCH"
          echo "VERSION=$VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Get merge commit message
        id: get_commit_message
        run: |
          MESSAGE=$(git log -1 --pretty=%B)
          echo "commit_message<<EOF" >> "$GITHUB_OUTPUT"
          echo "$MESSAGE" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.extract_version.outputs.version }}
          name: Release v${{ steps.extract_version.outputs.version }}
          body: ${{ steps.get_commit_message.outputs.commit_message }}
          draft: true
          prerelease: false
          files: |
            artifacts/**/*
